version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-faf1dyc8uy6u"
s3_prefix = "backend"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
